# Problem Sheet 9 - Tensors and their basic operations

**Submission until January 23 at 5 p.m. in the corresponding folder in StudIP.**

This exercise sheet is about tensors and their basic operations. Let's introduce a few important functions in `numpy` you may find useful for the following exercises and look at a few examples.

At first we consider `numpy.reshape`. This function is used to reshape a multi-dimensional array to another multi-dimensional array. The function `numpy.reshape` has the field `order` with which we are able to determine the type of ordering of the reshaping. If you set `order = "C"`, it corresponds to the lexicographic ordering (used in the programming language C) and if you set `order = "F"`, it corresponds to the colexicographic ordering (used in Fortran).

Execute the following code to see the difference between lexicographic and colexicographic ordering.

In [1]:
import numpy as np

A = np.arange(8).reshape((2,2,2), order="C")
print("Lexicographic ordering")
print("\n 1st frontal Slice of A:\n", A[:,:,0])
print("\n 2nd frontal Slice of A:\n", A[:,:,1])
B = np.arange(8).reshape((2,2,2), order="F")
print("\nColexicographic ordering")
print("\n 1st frontal Slice of B:\n", B[:,:,0])
print("\n 2nd frontal Slice of B:\n", B[:,:,1])

Lexicographic ordering

 1st frontal Slice of A:
 [[0 2]
 [4 6]]

 2nd frontal Slice of A:
 [[1 3]
 [5 7]]

Colexicographic ordering

 1st frontal Slice of B:
 [[0 2]
 [1 3]]

 2nd frontal Slice of B:
 [[4 6]
 [5 7]]


Now we consider `numpy.ravel`. This function is used to reshape a multi-dimensional array to an one-dimensional array. The function `numpy.ravel` has the field `order` with which we are able to determine the type of ordering of the vectorization. If you set `order = "C"`, it corresponds to the lexicographic ordering and if you set `order = "F"`, it corresponds to the colexicographic ordering.

Execute the following code to see the difference of vectorizing tensor `B` in lexicographic and colexicographic ordering.

In [2]:
print("Lexicographic ordering")
print("\n Vectorization:", np.ravel(B, order="C"))
print("\nColexicographic ordering")
print("\n Vectorization:", np.ravel(B, order="F"))

Lexicographic ordering

 Vectorization: [0 4 2 6 1 5 3 7]

Colexicographic ordering

 Vectorization: [0 1 2 3 4 5 6 7]


**Task: What happens if we do the same for $A$? (1 point)**

In [3]:
print("Lexicographic ordering")
print("\n Vectorization:", np.ravel(A, order="C"))
print("\nColexicographic ordering")
print("\n Vectorization:", np.ravel(A, order="F"))

Lexicographic ordering

 Vectorization: [0 1 2 3 4 5 6 7]

Colexicographic ordering

 Vectorization: [0 4 2 6 1 5 3 7]


It is always reversed

Lastly we consider the function `numpy.swapaxes`. This function is used to swap two dimensions of a multi-dimensional array. If we consider a two-dimensional array, then `numpy.swapaxes` is nothing else than `numpy.transpose`.

Execute the following code to see two examples of the function.

In [4]:
A = np.arange(10).reshape((2,5), order="F")
print("Matrix A:\n", A)
print("\nMatrix A with swapped axes 0 and 1:\n", np.swapaxes(A,0,1)) 
X =  np.arange(12).reshape((3,2,2), order="F")
print("\nTensor X:")
print("\n 1st frontal Slice of X:\n", X[:,:,0])
print("\n 2nd frontal Slice of X:\n", X[:,:,1])
print("\nTensor X with swapped axes 0 and 1:") 
print("\n 1st frontal Slice of X:\n", np.swapaxes(X,0,1)[:,:,0])
print("\n 2nd frontal Slice of X:\n", np.swapaxes(X,0,1)[:,:,1])

Matrix A:
 [[0 2 4 6 8]
 [1 3 5 7 9]]

Matrix A with swapped axes 0 and 1:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]

Tensor X:

 1st frontal Slice of X:
 [[0 3]
 [1 4]
 [2 5]]

 2nd frontal Slice of X:
 [[ 6  9]
 [ 7 10]
 [ 8 11]]

Tensor X with swapped axes 0 and 1:

 1st frontal Slice of X:
 [[0 1 2]
 [3 4 5]]

 2nd frontal Slice of X:
 [[ 6  7  8]
 [ 9 10 11]]


# Task 1: Creating a tensor

In this task we want to generate a tensor and get familiar with the functions introduced above.

A tensor can be represented in multiple ways. The simplest is the slice representation through multiple matrices.

Let's consider the tensor $X$ defined by its frontal slices:

$$
   X_1 = 
   \left[
   \begin{matrix}
   1  & 4  & 7  & 10 \\
   2  & 5 & 8 & 11 \\
   3 & 6 & 9 & 12
   \end{matrix}
   \right]
$$

and 

$$
   X_2 =
   \left[
   \begin{matrix}
   13  & 16  & 19  & 22 \\
   14  & 17 & 20 & 23 \\
   15 & 18 & 21 & 24
   \end{matrix}
   \right]
$$

**Task: Use `numpy.reshape` to generate the tensor $X$. Print the frontal slices and the column fibers of $X$. (1 points)**

In [5]:
X = np.arange(start=1, stop=25).reshape(3,4, 2, order="F")
print("Frontal Slices of X are: ")
# Frontal Slices
print(X[:, :, 0])
print("-------")
print(X[:, :, 1])

#Fibers
print("Fibers of X are: ")
for i in range(X[:, :, 0].shape[1]):
    print(X[:, i, 0])
    
for i in range(X[:, :, 1].shape[1]):
    print(X[:, i, 1])

Frontal Slices of X are: 
[[ 1  4  7 10]
 [ 2  5  8 11]
 [ 3  6  9 12]]
-------
[[13 16 19 22]
 [14 17 20 23]
 [15 18 21 24]]
Fibers of X are: 
[1 2 3]
[4 5 6]
[7 8 9]
[10 11 12]
[13 14 15]
[16 17 18]
[19 20 21]
[22 23 24]


In [6]:
X[:, :, 0].shape

(3, 4)

**Task: Use `numpy.ravel` to vectorize the tensor $X$ in lexicographic and colexicographic ordering. (1 points)**

In [7]:
print("Lexicographic ordering")
print("\n Vectorization:", np.ravel(X, order="C"))
print("\nColexicographic ordering")
print("\n Vectorization:", np.ravel(X, order="F"))

Lexicographic ordering

 Vectorization: [ 1 13  4 16  7 19 10 22  2 14  5 17  8 20 11 23  3 15  6 18  9 21 12 24]

Colexicographic ordering

 Vectorization: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]


**Task: Use `numpy.swapaxes` to restructre the tensor $X$ into a tensor of shape (4,3,2) and (2,4,3). Print the frontal slices of the new tensors. (1 points)**

In [8]:
X_new = X.reshape(2, 4, 3)

# Frontal Slices
print(X_new[:, :, 0])
print("-------")
print(X_new[:, :, 1])

[[ 1 16 10 14]
 [ 8 23  6 21]]
-------
[[13  7 22  5]
 [20  3 18 12]]


# Task 2: Outer product and Kronecker product

In this task we want to get familiar with the outer product and Kronecker product. So let's consider the definition of the two products.

The outer product of vectors $x^{(i)} \in \mathbb{R}^{n_{i}}, \ i = 1, \dots,d \ $ is the tensor

\begin{align*}
    X = x^{(1)} \circ x^{(2)} \circ \cdots \circ x^{(d)} \in \mathbb{R}^{n_{1} \times n_{2} \times \cdots \times n_{d}}
\end{align*}

defined by

\begin{align*}
    X(i_{1},i_{2},\dots,i_{d}) = x^{(1)}_{i_{1}} x^{(2)}_{i_{2}} \cdots x^{(d)}_{i_{d}} .
\end{align*}

The Kronecker product of matrix $A \in \mathbb{R}^{m \times n}$ and matrix $B \in \mathbb{R}^{p \times q}$ is given by

\begin{align*}
    A \otimes B = \left[ \begin{array}{rrr}
    a_{11}B & \cdots & a_{1n}B \\
\vdots & \ddots & \vdots \\
a_{m1}B & \cdots & a_{mn}B \\
\end{array} \right] \in \mathbb{R}^{mp \times nq}.
\end{align*}


At first we want to implement the outer product and apply the product to the vectors $x = (1,2,3) \in \mathbb{R}^{3}$, $y = (4,5) \in \mathbb{R}^{2}$ and $z = (6,7,8) \in \mathbb{R}^{3}$. 

**Task: Generate the vectors `x`, `y` and `z`. Implement a function, which computes the outer product of a tensor and a vector. Compute the outer product $ x \circ y \circ z$ and print the frontal slices. (3 points)** 

Hint: If you have a tensor $A \in \mathbb{R}^{n_{1} \times n_{2} \times \cdots \times n_{d}}$ and a vector $v\in \mathbb{R}^{n_{(d+1)}}$, then the outer product $X = A \circ v \in \mathbb{R}^{n_{1} \times n_{2} \times \cdots \times n_{(d+1)}}$ is given by
\begin{align*}
    X(:,:,\dots,:,i) = v_i \cdot A \qquad \forall i = 1,2,\dots,n_{(d+1)}.
\end{align*}
The outer product $P = x \circ y \circ z$ for the given vectors looks as follows:
\begin{align*}
    P(:,:,1) &= \left[ \begin{array}{rr}
    24 & 30  \\
48 & 60  \\
72 & 90  \\
\end{array} \right], \\
    P(:,:,2) &= \left[ \begin{array}{rr}
    28 & 35 \\
56 & 70 \\
84 & 105 \\
\end{array} \right], \\
    P(:,:,3) &= \left[ \begin{array}{rr}
    32 & 40 \\
64 & 80 \\
96 & 120 \\
\end{array} \right].
\end{align*}

In [9]:
def outer_product(tenso, vec):
    new = np.zeros(tenso.shape+tuple([vec.shape[0]])) #new tensor where the outer product will be saved
    for i in range((vec.shape[0])):
        new[..., i] = vec[i]*tenso #last dimension tensor element multiplication 
    return new

In [10]:
x = np.array([1,2,3])
y = np.array([4, 5])
z = np.array([6, 7, 8])
outer_prod = outer_product(outer_product(x, y), z)
print(f"The first slice: \n {outer_prod[:, :, 0]}")    
print(f"The second slice: \n {outer_prod[:, :, 1]}")    
print(f"The third slice: \n {outer_prod[:, :, 2]}")     

The first slice: 
 [[24. 30.]
 [48. 60.]
 [72. 90.]]
The second slice: 
 [[ 28.  35.]
 [ 56.  70.]
 [ 84. 105.]]
The third slice: 
 [[ 32.  40.]
 [ 64.  80.]
 [ 96. 120.]]


Now we implement the Kronecker product and apply the product to the matrices $A \in \mathbb{R}^{2 \times 2}$ and $B \in \mathbb{R}^{2 \times 3}$, i.e.

\begin{align*}
    A &= \left[ \begin{array}{rr}
    1 & 3  \\
2 & 4  \\
\end{array} \right],\\
    B &= \left[ \begin{array}{rrr}
    1 & 3 & 5 \\
2 & 4 & 6 \\
\end{array} \right].
\end{align*}

**Task: Generate the matrices $A$ and $B$. Implement a function, which computes the Kronecker product for two arrays. Compute the Kronecker product $A \otimes B$ and print the resulting matrix. (3 points)**

Hint: Keep in mind, that your function should be able to compute the Kronecker product of two matrices, two vectors or one vector and one matrix.
The Kronecker product $A \otimes B$ for the given matrices looks as follows:

\begin{align*}
    A \otimes B &= \left[ \begin{array}{rrrrrr}
    1 & 3 & 5 & 3 & 9 & 15 \\
    2 & 4 & 6 & 6 & 12 & 18  \\
    2 & 6 & 10 & 4 & 12 & 20 \\
    4 & 8 & 12 & 8 & 16 & 24 \\
\end{array} \right] \in \mathbb{R}^{4 \times 6}.
\end{align*}

In [11]:
def kronecker_product(a, b):
    arr_blocks=[] # List of Matrix blocks to be reshaped
    
    if(len(a.shape)==1):
        a = a[:, None]
    if(len(b.shape)==1):
        b = b[:, None] 
    shp =  a.shape[1]
    for i in range(len(a.flatten())):
        arr_blocks.append(a.flatten()[i]*b)
        
    tmp = arr_blocks[0]
    
    # The Blocks are concateneated horizontally firtly by the number of columns of A
    block_horiz=[]
    for i in range(1, len(arr_blocks)+1):
        if ((i%shp)!=0):
            tmp = np.hstack((tmp,  arr_blocks[i]))
        else:
            block_horiz.append(tmp)
            if(i!=len(arr_blocks)):
                tmp = arr_blocks[i]
           
    # Blocks are now concatenated verically to get the whole matrix
    block_vert = block_horiz[0]
    for i in range(1, len(block_horiz)):
        block_vert = np.vstack((block_vert,block_horiz[i]))
    return block_vert

In [12]:
a = np.array([[1, 3], [2,4]])
b = np.array([[1,3, 5],[2, 4, 6]])
kronecker_product(a, b)

array([[ 1,  3,  5,  3,  9, 15],
       [ 2,  4,  6,  6, 12, 18],
       [ 2,  6, 10,  4, 12, 20],
       [ 4,  8, 12,  8, 16, 24]])

Now that we have implemented the outer product und Kronecker product, we are able to check the relation between the two. From the lecture we know for $x^{(i)} \in \mathbb{R}^{n_{i}}, \ i = 1, \dots,d$ it holds

\begin{align*}
    \mathrm{vec} \left(  x^{(1)} \circ x^{(2)} \circ \cdots \circ x^{(d)} \right) = x^{(d)} \otimes x^{(d-1)} \otimes \cdots \otimes x^{(1)}.
\end{align*}

Here we have to be careful since this equation is only valid if the vectorization follows the colexicographic ordering. \
If we consider lexicographic ordering for the vectorization, we would obtain

\begin{align*}
    \mathrm{vec} \left(  x^{(1)} \circ x^{(2)} \circ \cdots \circ x^{(d)} \right) = x^{(1)} \otimes x^{(2)} \otimes \cdots \otimes x^{(d)}.
\end{align*}

We want to check both equations for the given vectors `x`, `y ` and `z`.

**Task: Use the `np.ravel` function to vectorize your product and check that the two equations above are true for the given vectors `x`, `y` and `z` from the previous part. (2 points)**

Hint: The `np.ravel` function has the field `order`. If you set `order = "C"`, it corresponds to the lexicographic ordering and if you set `order = "F"`, it corresponds to the colexicographic ordering.

In [13]:
# The equtions are true
print(np.sum(np.ravel(outer_product(outer_product(x,y),z), order="F") - kronecker_product(z,kronecker_product(y,x))))

0.0


In [14]:
print(np.sum(np.ravel(outer_product(outer_product(x,y),z), order="C") - kronecker_product(x,kronecker_product(y,z))))

0.0


# Task 3: Mode-k product

In this task we want to consider the mode-k product. So let's have a look at the definition.
Let $X \in \mathbb{R}^{n_{1} \times n_{2} \times \cdots \times n_{d}}$ be a tensor and $A\in \mathbb{R}^{m \times n_{k}}$ a matrix. The multiplication of each mode-k fiber by A is called the mode-k product

\begin{align*}
    X \times_{k} A \in \mathbb{R}^{n_{1} \times \cdots \times n_{k-1} \times m \times n_{k+1} \times \cdots \times n_{d}}
\end{align*}

This is defined elementwise by

\begin{align*}
    (X \times_{k} A )(i_{1},\dots,i_{k-1},j,i_{k+1},\dots,i_{d}) = \sum\limits_{i_{k}=1}^{n_{k}} X(i_{1},\dots,i_{k-1},i_{k},i_{k+1},\dots,i_{d}) A(j,i_{k}) \\
    \forall \ i_{l} = 1, \dots,n_{l} \ \mathrm{and} \ j = 1,\dots,m \ \ \mathrm{s.t.} \ l \in \lbrace 1,\dots,d \rbrace \! \setminus \! \lbrace k \rbrace
\end{align*}

One can compute the mode-k product in a more direct way. To apply this we have to look at the mode-k unfolding. The mode-k unfolding is the matricization of a tensor $X$ and it is denoted as $X_{(k)}$. $X_{(k)}$ contains the mode-k fibers as columns in a colexicographic ordering. You can see a nice picture about that in the lecture on page 43 of the file `MMDS_5-Tensor_Factorizations-I-1.pdf`. Now we have

\begin{align*}
    (X \times_{k} A )_{(k)} = A \cdot X_{(k)}.
\end{align*}

To obtain $X \times_{k} A$ we only have to reshape $A \cdot X_{(k)}$.

At first we want to implenent the mode-k product and apply the product to the above defined tensor $X \in \mathbb{R}^{3 \times 4 \times 2}$ and the matrix $A \in \mathbb{R}^{3 \times 2}$, given as

\begin{align*}
    A &= \left[ \begin{array}{rr}
    1 & 0  \\
0 & 2  \\
1 & 1 
\end{array} \right].
\end{align*}

**Task: Generate the matrix $A$. Implement the mode-k product and compute the mode-3 product $X \times_{3} A$. Print the frontal slices of $X \times_{3} A$. (4 points)**

Hint: Use the function `numpy.swapaxes` to restructure your tensor and then apply `numpy.reshape` to obtain the mode-k unfolding.

In [15]:
def modek_prod(tensor, matrix, mode):
    return np.swapaxes(np.swapaxes(tensor, mode - 1, -1).dot(matrix.T), mode - 1, -1)

In [16]:
a = np.array([[1, 0], [0,2], [1,1]])

In [17]:
print(X.shape)
print(modek_prod(X, a , 3).shape)
modek_ex = modek_prod(X, a , 3)
print(f"The first slice: \n {modek_ex[:, :, 0]}")    
print(f"The second slice: \n {modek_ex[:, :, 1]}")    
print(f"The third slice: \n {modek_ex[:, :, 2]}")    

(3, 4, 2)
(3, 4, 3)
The first slice: 
 [[ 1  4  7 10]
 [ 2  5  8 11]
 [ 3  6  9 12]]
The second slice: 
 [[26 32 38 44]
 [28 34 40 46]
 [30 36 42 48]]
The third slice: 
 [[14 20 26 32]
 [16 22 28 34]
 [18 24 30 36]]


In the lecture we have seen the following relation between the mode-k product and the kronecker product. Let $X \in \mathbb{R}^{n_{1} \times n_{2} \times \cdots \times n_{d}}$ be a tensor and $A_{k} \in \mathbb{R}^{m_{k} \times n_{k}}$ be matrices for $k=1,\dots,d$. Then it holds 

\begin{align*}
    \mathrm{vec} \big( X \times_{1} A_{1} \times_{2} A_{2} \times_{3} \cdots \times_{d} A_{d} \big) = \big( A_{d} \otimes A_{d-1} \otimes \cdots \otimes A_{1} \big) \mathrm{vec}(X).
\end{align*}

Here we have to be careful since this equation is only valid if the vectorization follows the colexicographic ordering. 
If we consider lexicographic ordering for the vectorization, we would obtain

\begin{align*}
    \mathrm{vec} \big( X \times_{1} A_{1} \times_{2} A_{2} \times_{3} \cdots \times_{d} A_{d} \big) = \big( A_{1} \otimes A_{2} \otimes \cdots \otimes A_{d} \big) \mathrm{vec}(X).
\end{align*}

We want to check both equations for certain matrices $A_{1}, A_{2}$ and $A_{3}$ and the known tensor $X$. In the following we consider
\begin{align*}
        A_{1} &= \left[ \begin{array}{rrr}
    1 & 0 & 1  \\
    1 & 2 & 1  \\
    1 & 0 & 3  \\
    2 & 0 & 0  \\
    1 & 1 & 1 
\end{array} \right], \\
        A_{2} &= \left[ \begin{array}{rrrr}
    1 & 0 & 2 & 0 \\
    0 & -1 & 0 & -2
\end{array} \right], \\
A_{3} &= \left[ \begin{array}{rr}
    0 & 2  \\
    -1 & 0 
\end{array} \right].
\end{align*}

**Task: Use the `np.ravel` function to vectorize your product and check that both equations above are true for the given matrices $A_{1}$, $A_{2}$, $A_{3}$ and the tensor $X$. (2 points)**

Hint: The `np.ravel` function has the field `order`. If you set `order = "C"`, it corresponds to the lexicographic ordering and if you set `order = "F"`, it corresponds to the colexicographic ordering.

In [18]:
A_1 = np.array([[1,0,1],[1,2,1],[1,0,3],[2,0,0],[1,1,1]])
A_2 = np.array([[1,0,2,0],[0,-1,0,-2]])
A_3 = np.array([[0,2],[-1,0]])

In [19]:
# Equations is valid and we check it hier

print(np.sum(np.ravel(modek_prod(modek_prod(modek_prod(X, A_1, 1), A_2, 2), A_3, 3), order="F")
-kronecker_product(kronecker_product(A_3, A_2), A_1).dot(np.ravel(X, order="F")))) #colex first equation

print(np.sum(np.ravel(modek_prod(modek_prod(modek_prod(X, A_1, 1), A_2, 2), A_3, 3), order="C")
-kronecker_product(kronecker_product(A_1, A_2), A_3).dot(np.ravel(X, order="C")))) #lex second equation

0
0


# Task 4: Khatri-Rao product

In this task we consider the Khatri-Rao product. So let's have a look at the definition. The Khatri-Rao product $A \odot B$ of the two matrices $A \in \mathbb{R}^{m,n}$ and $B \in \mathbb{R}^{p,n}$ is given as

\begin{align*}
    A \odot B = \big[A(:,1) \otimes B(:,1) \ \ A(:,2) \otimes B(:,2) \ \ \cdots \ \ A(:,n) \otimes B(:,n) \big] \in \mathbb{R}^{mp \times n }.
\end{align*}

At first we want to implenent the Khatri-Rao product and apply the product to two given matrices $A$ and $B$. In the following we consider

\begin{align*}
 A &= \left[ \begin{array}{rrrr}
    3 & 1 & 3 & 0 \\
    0 & -1 & -1 & 0 \\
    1 & -1 & 2 & 3
\end{array} \right], \\
B &= \left[ \begin{array}{rrrr}
    0 & 2 & 0 & 4 \\
    1 & 2 & 4 & 8 
\end{array} \right].
\end{align*}

**Task: Write a function that takes two matrices with the same number of columns as an input and returns their Khatri-Rao product. Compute the Khatri-Rao product $A \odot B$ and plot the resulting matrix. (2 points)**

Hint: Use your implemented function which computes the Kronecker product.

In [20]:
A = np.array([[3,1,3,0],[0,-1,-1,0],[1,-1,2,3]])
B = np.array([[0,2,0,4],[1,2,4,8]])

In [21]:
def khatri_rao(a, b):
    return [kronecker_product(a[:, i], b[:, i]) for i in range(a.shape[1])]

In [22]:
khatri_rao(A, B)

[array([[0],
        [3],
        [0],
        [0],
        [0],
        [1]]),
 array([[ 2],
        [ 2],
        [-2],
        [-2],
        [-2],
        [-2]]),
 array([[ 0],
        [12],
        [ 0],
        [-4],
        [ 0],
        [ 8]]),
 array([[ 0],
        [ 0],
        [ 0],
        [ 0],
        [12],
        [24]])]

In [41]:
a = np.arange(1, 19).reshape(3,3,2, order="f")

In [57]:
b = np.arange(1, 13).reshape((2,3,2), order="f")

In [66]:
np.tensordot(a, b, axes=([2], [0])).shape

(3, 3, 3, 2)

In [71]:
a = np.arange(60.).reshape(3,4,5)
b = np.arange(24.).reshape(4,3,2)
c = np.tensordot(a,b, axes=([1,0],[0,1]))

In [72]:
c

array([[4400., 4730.],
       [4532., 4874.],
       [4664., 5018.],
       [4796., 5162.],
       [4928., 5306.]])

In [73]:
d = np.tensordot(a,b, axes=([0,1],[1,0]))

In [74]:
d

array([[4400., 4730.],
       [4532., 4874.],
       [4664., 5018.],
       [4796., 5162.],
       [4928., 5306.]])